import json,csv,os,re,statistics as st,collections,unicodedata
S=os.path.dirname(os.path.abspath(__file__))
OUT="/Users/chaitanyaparwatkar/Desktop/release/edaic_rerun/AUDIT_1a1c_ad.txt"
D=json.load(open(S+'/part1a.json')); DUR=json.load(open(S+'/durations.json')); KOFF=json.load(open(S+'/kcl_offsets.json'))
B="/Volumes/G-Drive Pro/paper work/Hard drive data for paper"; DB=B+"/DementiaBank"
P="/Volumes/G-Drive Pro/paper1_local_runs"
pitt=D['pitt']; adso=D['adso']; a20=D['a20']
L=[]
def w(s=""): L.append(s)
def f(x,n=4): return "NA" if x is None else f"{x:.{n}f}"
def pct(a,b): return f"{a}/{b} = {a/b:.4f}"
def norm(t):
    t=unicodedata.normalize('NFKD',t.lower()); t=''.join(c for c in t if not unicodedata.combining(c))
    return ' '.join(re.sub(r'[^a-z ]',' ',t).split())

w("="*100)
w("PART 1c  NON-E-DAIC CLAIMS, AD AND PD HALF")
w("Format: CLAIM / DATA / VERDICT. Claim wording taken from")
w("  .../share_for_minoo/PROTOCOL.md and from the counts the draft uses.")
w("="*100)
w()

# ---- C1
w("-"*100); w("C1  'every Parkinson's speaker reads the same passage'"); w("-"*100)
w("CLAIM  PROTOCOL.md, Transcripts section, verbatim:")
w("       'Read speech (KCL, PC-GITA, Neurovoz): everyone reads the same passage, no transcripts needed.'")
w("DATA   Counted from the ASR transcripts we hold and from the clip paths in them.")
w()
pg=list(csv.DictReader(open('/Users/chaitanyaparwatkar/Desktop/release/part4_text/asr/asr_pcgita.csv')))
c=collections.Counter(r['clip_path'].split('/spanish_dataset/')[-1].rsplit('/',1)[0] for r in pg)
prompts=sorted(set(k.split('/')[1] for k in c))
w(f"  PC-GITA  /Users/chaitanyaparwatkar/Desktop/release/part4_text/asr/asr_pcgita.csv, {len(pg)} rows")
w(f"    distinct prompt folders in the scored set: {len(prompts)}  -> {', '.join(prompts)}")
w("    task families: 1 read-text passage (ayerfuialmedico) + 10 fixed single sentences (sentences/, sentences2/)")
w(f"    clips per prompt: 100 for each of the {len(prompts)} prompts (50 HC + 50 PD), {len(prompts)}*100 = {len(prompts)*100}")
w(f"    the read-text passage is only {pct(100,len(pg))} of the scored PC-GITA clips")
t=[norm(r['text']) for r in pg]
w(f"    distinct exact normalised ASR strings: {len(set(t))};  distinct first-5-word keys: {len(set(' '.join(x.split()[:5]) for x in t))}")
w(f"    distinct speakers: {len(set(r['speaker_id'] for r in pg))} (11 clips per speaker, one per prompt);  labels {dict(collections.Counter(r['label'] for r in pg))}")
w()
nv=list(csv.DictReader(open('/Users/chaitanyaparwatkar/Desktop/release/part4_text/asr/asr_neurovoz.csv')))
pr=collections.Counter(os.path.basename(r['clip_path']).split('_')[1] for r in nv)
w(f"  NeuroVoz  .../asr_neurovoz.csv, {len(nv)} rows")
w(f"    distinct prompts, taken from the fixed token in the filename HC|PD_<PROMPT>_<id>.wav: {len(pr)}")
w(f"    -> {', '.join(k+'('+str(v)+')' for k,v in sorted(pr.items()))}")
t=[norm(r['text']) for r in nv]
w(f"    distinct exact normalised ASR strings: {len(set(t))};  distinct first-5-word keys: {len(set(' '.join(x.split()[:5]) for x in t))}")
w(f"    distinct speakers: {len(set(r['speaker_id'] for r in nv))} (about 12 clips per speaker, one per prompt);  labels {dict(collections.Counter(r['label'] for r in nv))}")
w()
kc=list(csv.DictReader(open('/Users/chaitanyaparwatkar/Desktop/release/part4_text/asr/asr_kcl.csv')))
t=[norm(r['text']) for r in kc]
k5=collections.Counter(' '.join(x.split()[:5]) for x in t)
w(f"  MDVR-KCL  .../asr_kcl.csv, {len(kc)} rows, one per speaker")
w(f"    distinct exact normalised ASR strings: {len(set(t))} of {len(kc)}")
w(f"    distinct first-5-word keys: {len(k5)} of {len(kc)}")
w(f"    most common opening: '{k5.most_common(1)[0][0]}' in only {k5.most_common(1)[0][1]}/{len(kc)} clips")
w("    The KCL read recordings contain more than one text. Openings seen include the start of the North Wind")
w("    passage and the start of a technical paragraph about sunlight (the observer's altitude, Figure 5.7).")
w("    One clip transcribes to a single word.")
ko=[v[0] for v in KOFF.values()]
w(f"    Because the 30 s window starts anywhere from {f(min(ko))} s to {f(max(ko))} s into the reading (1a.4),")
w("    different speakers are scored on different sentences even where the underlying script is shared.")
w()
w("VERDICT  MISMATCH.")
w("  PC-GITA: 11 distinct prompts, not one passage. NeuroVoz: 12 distinct prompts, not one passage.")
w("  MDVR-KCL: one recording per speaker, but the scored 30 s lands in a different place for each")
w("  speaker, so the read text inside the scored window is not held constant either.")
w("  The sentence as written in PROTOCOL.md is not supported by any of the three sets.")
w()

# ---- C2
w("-"*100); w("C2  '468 thirty-second segments'"); w("-"*100)
w("CLAIM   the Pitt scored set is 468 thirty-second segments.")
w("DATA    ffprobe on all 468 files in .../DementiaBank/segments/ (listed by")
w("        /Volumes/G-Drive Pro/paper1_local_runs/pitt_manifest.csv, 468 rows).")
sd=sorted(r['seg_dur'] for r in pitt)
def quant(xs,fr):
    i=fr*(len(xs)-1); lo=int(i); return xs[lo]+(xs[min(lo+1,len(xs)-1)]-xs[lo])*(i-lo)
w("  Pitt scored-segment length distribution, seconds:")
for lbl,fr in [("min",0),("p5",.05),("p10",.10),("p25",.25),("median",.5),("p75",.75),("p90",.90),("p95",.95),("max",1.0)]:
    w(f"      {lbl:>6}  {f(quant(sd,fr))}")
w(f"      mean {f(st.mean(sd))}   sd {f(st.pstdev(sd))}")
b=collections.Counter()
for x in sd:
    k=int(x//5)*5; b[k]+=1
w("  binned: " + "  ".join(f"[{k},{k+5}) {v}" for k,v in sorted(b.items())))
w(f"  segments within 0.5000 s of 30 s: {pct(sum(1 for x in sd if abs(x-30)<=0.5),468)}")
w("  segments exactly 30.0000 s: 0/468.  shorter than 30 s: 0/468.  longer than 30 s: 468/468.")
w("  WHERE THE 30 s IS ACTUALLY APPLIED:")
w("    not in Pitt. cut_segments.py cuts [start_ms, end_ms] straight from pitt_conflict_manifest.csv;")
w("    30 s never appears in that script. PROTOCOL.md says the same: 'Pitt segments are cut at the")
w("    manifest's start_ms/end_ms'. The 468 clips are conflict/agreement spans of variable length.")
w(f"    ADReSSo    prep_adresso.py / recut_at_patient.py pass ffmpeg -t 30: {sum(1 for r in adso if abs(r['seg_dur']-30)<0.005)}/237 are exactly 30.0000 s,"
  f" {sum(1 for r in adso if r['seg_dur']<29.995)}/237 shorter because the recording ended.")
w(f"    ADReSS-2020 same script: {sum(1 for r in a20 if abs(r['seg_dur']-30)<0.005)}/156 exactly 30.0000 s, {sum(1 for r in a20 if r['seg_dur']<29.995)}/156 shorter.")
w("    MDVR-KCL   37/37 exactly 30.0000 s.")
w("VERDICT  MISMATCH on 'thirty-second'. MATCH on '468'.")
w("  468 is right. The median Pitt segment is 33.2850 s and the longest is 55.5600 s. Calling them")
w("  thirty-second segments understates the audio by 15 percent at the median.")
w()

# ---- C3
w("-"*100); w("C3  speaker counts 228 (Pitt), 237 (ADReSSo), 156 (ADReSS-2020)"); w("-"*100)
w("CLAIM   Pitt 228 speakers, ADReSSo 237 speakers, ADReSS-2020 156 speakers.")
w("DATA")
sp=set((r['grp'],r['spk']) for r in pitt)
w(f"  Pitt: distinct (group, speaker id) over the 468 scored rows = {len(sp)}")
w(f"        by group: {dict(collections.Counter(g for g,_ in sp))}")
w(f"        cross-check, distinct 'speaker' strings in pitt_manifest.csv = {len(set(r['speaker'] for r in csv.DictReader(open(P+'/pitt_manifest.csv'))))}")
w(f"        WATCH OUT: distinct bare numeric ids, ignoring group, = {len(set(r['spk'] for r in pitt))}. One numeric id is reused")
w("        across Control and Dementia, so any grouping key must be group+id, not the id alone.")
w(f"        468 clips come from {len(set(r['session'] for r in pitt))} distinct recordings and {len(sp)} speakers.")
w(f"        clips per speaker: {dict(sorted(collections.Counter(collections.Counter((r['grp'],r['spk']) for r in pitt).values()).items()))}"
  f"   (read as 'n clips: n speakers'; the busiest speaker contributes 9 of the 468 clips)")
w(f"        recordings per speaker: {dict(sorted(collections.Counter(collections.Counter(k[0:2] for k in set((r['grp'],r['spk'],r['session']) for r in pitt)).values()).items()))}")
w(f"  ADReSSo: distinct spk in adresso_manifest_patient.csv = {len(set(r['spk'] for r in adso))}, rows = {len(adso)} (one clip per speaker)")
w(f"           labels {dict(collections.Counter(r['label'] for r in adso))}")
w(f"  ADReSS-2020: distinct spk = {len(set(r['spk'] for r in a20))}, rows = {len(a20)} (one clip per speaker)")
w(f"           labels {dict(collections.Counter(r['label'] for r in a20))}")
w("VERDICT  MATCH for all three (228 / 237 / 156).")
w("  Caveat worth one line in the paper: Pitt 228 speakers but 468 clips, up to 9 clips from one speaker,")
w("  so any split must be grouped by speaker or the numbers are optimistic.")
w()

# ---- C4
w("-"*100); w("C4  '108 plus 48 split'"); w("-"*100)
w("CLAIM   a 108 + 48 split. Nothing in the draft says which dataset, so it was resolved from the files.")
w("DATA    It is ADReSS-2020. .../adress2020/adress2020_manifest_patient.csv has a 'split' column:")
c=collections.Counter(r['split'] for r in a20)
w(f"        train {c['train']}, test {c['test']}, total {sum(c.values())}")
w("        This matches the released ADReSS-2020 challenge structure: the training set is the")
w("        108-speaker balanced set and the test set is 48 speakers.")
lb=collections.Counter((r['split'],r['label']) for r in a20)
for k in sorted(lb): w(f"        {k[0]:<6} label {k[1]}: {lb[k]}")
w("        Both splits are label balanced: 54/54 in train, 24/24 in test.")
w("        No other dataset here splits 108/48. Pitt is 146/322, ADReSSo is a single 237 block.")
w("VERDICT  MATCH. 108 + 48 = 156, and it is the ADReSS-2020 train/test split.")
w("  One caution: both splits are pooled into a single 156-clip scoring set. The 108/48 boundary is")
w("  not used as a train/test boundary anywhere in the probing runs, so quoting it as a split is")
w("  describing the corpus, not describing our evaluation.")
w()

# ---- C5
w("-"*100); w("C5  'the 30 s window starts at the patient's first words' on the three AD sets"); w("-"*100)
w("CLAIM   PROTOCOL.md, Window section, verbatim:")
w("        'ADReSSo, ADReSS-2020 and KCL: 30 s starting at the patient's first words (the interviewer's")
w("        prompt is skipped using Whisper segment timestamps; scripts/adresso/recut_at_patient.py).'")
w("DATA    What recut_at_patient.py actually does, read from the script on disk:")
w("        it transcribes the first 75 s with faster-whisper small.en, scans ASR segments that begin")
w("        before 45 s, matches their text against a fixed regex of prompt phrases, and sets the start")
w("        to the END of the LAST matching segment, capped at 45 s. If no segment matches, start = 0.0.")
w("        So the rule is 'end of the last detected prompt', not 'the participant's first word'. Those")
w("        two coincide only when the prompt runs right up to the participant's first syllable.")
w()
w("  ADReSS-2020 (156 clips, ground-truth CHAT timings available, so this is checkable):")
ok={}
for tol in [0.1,0.25,0.5,1.0,2.0]:
    ok[tol]=sum(1 for r in a20 if r['first_par_s'] is not None and abs(r['w0']-r['first_par_s'])<=tol)
for tol in [0.1,0.25,0.5,1.0,2.0]:
    w(f"      windows whose start is within {f(tol,2)} s of the first *PAR: word: {pct(ok[tol],156)}")
w(f"      windows starting EXACTLY at the first *PAR: word (delta 0.0000): {pct(sum(1 for r in a20 if abs(r['w0']-r['first_par_s'])<1e-9),156)}")
dif=[r['w0']-r['first_par_s'] for r in a20]
w(f"      start minus first participant word, seconds: min {f(min(dif))}  median {f(st.median(dif))}  mean {f(st.mean(dif))}  max {f(max(dif))}")
w(f"      window starts LATE, more than 0.5 s after the participant began: {pct(sum(1 for d in dif if d>0.5),156)}  (participant speech is cut off the front)")
w(f"      window starts EARLY, more than 0.5 s before the participant began: {pct(sum(1 for d in dif if d<-0.5),156)}  (prompt is inside the window)")
w(f"      windows starting at 0.0000 s, i.e. the detector found no prompt at all: {pct(sum(1 for r in a20 if r['w0']==0.0),156)}")
w(f"      and the direct consequence, from 1a.3: {pct(sum(1 for r in a20 if r['inv_certain']>0),156)} windows contain interviewer words.")
w()
w("  ADReSSo (237 clips): CANNOT BE VERIFIED FROM TIMINGS. No timed transcript exists anywhere in")
w("      .../challenges/ADReSS-M (searched the whole tree; only mp3s, meta and groundtruth csvs).")
w("      What can be said from files that do exist:")
w(f"        windows starting at 0.0000 s, so no prompt was detected and no shift was applied: {pct(sum(1 for r in adso if r['w0']==0.0),237)}")
adt=list(csv.DictReader(open(B+'/adresso/adresso_transcripts_patient.csv')))
PR=re.compile(r"(tell me|everything (that )?you see|going on in (this|that|the) picture|what do you see|here.s (the|a) picture|look at (this|that|the) picture|what.s happening|all (of )?the action|describe)", re.I)
hit=[r for r in adt if PR.search(r['text'][:200])]
w(f"        clips whose own ASR still opens with a prompt phrase: {pct(len(hit),237)} -> {', '.join(sorted(r['spk'] for r in hit))}")
w("        That is a lower bound on prompt leakage, because the same regex that missed the prompt at")
w("        cut time is the one being used to look for it now.")
w()
w("  Pitt (468 clips): the claim is not made for Pitt, and the result is the opposite of what you would expect.")
dp=[r['w0']-r['first_par_s'] for r in pitt if r['first_par_s'] is not None]
w(f"        Pitt windows starting EXACTLY at the first *PAR: word: {pct(sum(1 for d in dp if abs(d)<1e-9),468)}")
w(f"        start minus first participant word: min {f(min(dp))}  median {f(st.median(dp))}  mean {f(st.mean(dp))}  max {f(max(dp))}")
w(f"        by arm: conflict {pct(sum(1 for r in pitt if r['set']=='conflict' and abs(r['w0']-r['first_par_s'])<1e-9),146)},"
  f" agreement {pct(sum(1 for r in pitt if r['set']=='agreement' and abs(r['w0']-r['first_par_s'])<1e-9),322)}")
w("        The conflict/agreement spans were cut on utterance boundaries, and for two thirds of them")
w("        that boundary IS the participant's first utterance. The remaining 154 start later, up to")
w("        216.0240 s into the recording.")
w("        So Pitt, where the first-words rule was never claimed, satisfies it 67 percent of the time,")
w("        and ADReSS-2020, where it was claimed, satisfies it 19 percent of the time.")
w()
w("  MDVR-KCL (37 clips): the protocol sentence covers KCL too. Measured offsets (1a.4):")
w(f"        start offsets range {f(min(ko))} to {f(max(ko))} s, median {f(st.median(ko))} s.")
w(f"        clips starting at 0.0000 s: {sum(1 for x in ko if x==0.0)}/37. KCL read recordings open with phone-setup")
w("        talk, which is why the clips were re-cut at all; the README in clips_for_af3 says so.")
w("VERDICT  MISMATCH.")
w(f"  On the one AD set where it can be checked against ground truth, ADReSS-2020, only {pct(ok[0.25],156)}")
w("  of windows start within a quarter second of the participant's first word, and 114/156 contain")
w("  interviewer speech. On ADReSSo the claim is unverifiable from disk. The honest wording is")
w("  'the window starts after the last automatically detected interviewer prompt, or at 0 s when no")
w("  prompt was detected'.")
w()

# ---- C6
w("-"*100); w("C6  Pitt conflict set: 146 + 322"); w("-"*100)
w("CLAIM   the Pitt conflict set is 146 + 322.")
w("DATA    'set' column of /Volumes/G-Drive Pro/paper1_local_runs/pitt_manifest.csv (468 rows):")
c=collections.Counter(r['set'] for r in csv.DictReader(open(P+'/pitt_manifest.csv')))
w(f"        conflict {c['conflict']}, agreement {c['agreement']}, total {sum(c.values())}")
c2=collections.Counter(r['set'] for r in pitt)
w(f"        same counts from pitt_conflict_manifest.csv: conflict {c2['conflict']}, agreement {c2['agreement']}")
lb=collections.Counter((r['set'],r['label']) for r in pitt)
for k in sorted(lb): w(f"        {k[0]:<10} label {k[1]}: {lb[k]}")
w(f"        distinct speakers in the conflict arm: {len(set((r['grp'],r['spk']) for r in pitt if r['set']=='conflict'))}")
w(f"        distinct speakers in the agreement arm: {len(set((r['grp'],r['spk']) for r in pitt if r['set']=='agreement'))}")
w(f"        speakers appearing in BOTH arms: {len(set((r['grp'],r['spk']) for r in pitt if r['set']=='conflict') & set((r['grp'],r['spk']) for r in pitt if r['set']=='agreement'))}")
w("VERDICT  MATCH. 146 conflict + 322 agreement = 468.")
w("  Note for the paper: the two arms are not speaker-disjoint, and both arms carry interviewer")
w("  speech at similar rates:")
for s in ['conflict','agreement']:
    arm=[r for r in pitt if r['set']==s]
    w(f"        {s:<10} windows containing interviewer words: {pct(sum(1 for r in arm if r['inv_certain']>0),len(arm))}")
w()
w("="*100)
w("WHAT COULD NOT BE CHECKED, AND WHY")
w("="*100)
w("  1. Participant vs interviewer word counts inside the ADReSSo window. No timed transcript exists")
w("     under .../challenges/ADReSS-M. The ADReSSo folder under challenges/ is empty. Only whisper ASR")
w("     of the already-cut clips exists, and it carries no speaker labels and no timings.")
w("  2. Word counts inside the MDVR-KCL window. The KCL tree is audio only.")
w("  3. Where the PC-GITA and NeuroVoz 'window' starts. There is no window: each scored file is one")
w("     whole short prompt recording, median 3.4240 s and 2.9722 s. Nothing is cut.")
w("  4. Whether the ADReSS-2020 Full_wave_enhanced_audio timeline is the raw recording timeline. The")
w("     CHAT last timestamp over audio length is median 0.9945 (min 0.8975, max 1.0757), so it is the")
w("     same clock to within a few percent, but the enhanced audio is a processed release and the last")
w("     few percent are not provable from what is on disk.")
w("  5. Nothing under any omni_final directory was read or written, per the task constraints.")
w()
open(OUT,'a').write("\n".join(L)+"\n")
print("appended 1c,",len(L),"lines")
